name: Build Gorilla Tag Mod

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'

    - name: Compile Mod directly
      run: |
        mkdir -p output
        csc -target:library -out:output/VerityMonster.dll AllMods.cs -reference:/usr/share/dotnet/sdk/6.0.428/ref/net472/mscorlib.dll

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: CustomMod-dll
        path: output/
