name: Build Gorilla Tag Mod

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'

    - name: Build with dotnet
      run: dotnet build Mods.csproj --configuration Release

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: CustomMod-dll
        path: bin/Release/net472/
